//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace FamoCity.PersonalService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FamoPersonalServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FamoPersonalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFriendsRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFriendsRequestsSeeMoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFriendsRequestsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCustomerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccetpFriendShipOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelFriendShipOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastNotificationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncreaseNotificationCounterOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotificationsCountZeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNotificationCountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FamoPersonalService() {
            this.Url = global::FamoCity.Properties.Settings.Default.FamoCity_PersonalService_FamoPersonalService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegisterNewUserCompletedEventHandler RegisterNewUserCompleted;
        
        /// <remarks/>
        public event GetFriendsRequestsCompletedEventHandler GetFriendsRequestsCompleted;
        
        /// <remarks/>
        public event GetFriendsRequestsSeeMoreCompletedEventHandler GetFriendsRequestsSeeMoreCompleted;
        
        /// <remarks/>
        public event GetFriendsRequestsCountCompletedEventHandler GetFriendsRequestsCountCompleted;
        
        /// <remarks/>
        public event GetCustomerDataCompletedEventHandler GetCustomerDataCompleted;
        
        /// <remarks/>
        public event SaveCustomerInfoCompletedEventHandler SaveCustomerInfoCompleted;
        
        /// <remarks/>
        public event AccetpFriendShipCompletedEventHandler AccetpFriendShipCompleted;
        
        /// <remarks/>
        public event CancelFriendShipCompletedEventHandler CancelFriendShipCompleted;
        
        /// <remarks/>
        public event GetLastNotificationsCompletedEventHandler GetLastNotificationsCompleted;
        
        /// <remarks/>
        public event GetCustomerLinkCompletedEventHandler GetCustomerLinkCompleted;
        
        /// <remarks/>
        public event IncreaseNotificationCounterCompletedEventHandler IncreaseNotificationCounterCompleted;
        
        /// <remarks/>
        public event NotificationsCountZeroCompletedEventHandler NotificationsCountZeroCompleted;
        
        /// <remarks/>
        public event GetNotificationCountsCompletedEventHandler GetNotificationCountsCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterNewUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RegisterNewUser(string admEmail, string admPassword, int CustomerId, string CustomerEmail, string CustomerPassword, string FirstName, string LastName, int Gender, int BirthDate) {
            object[] results = this.Invoke("RegisterNewUser", new object[] {
                        admEmail,
                        admPassword,
                        CustomerId,
                        CustomerEmail,
                        CustomerPassword,
                        FirstName,
                        LastName,
                        Gender,
                        BirthDate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterNewUserAsync(string admEmail, string admPassword, int CustomerId, string CustomerEmail, string CustomerPassword, string FirstName, string LastName, int Gender, int BirthDate) {
            this.RegisterNewUserAsync(admEmail, admPassword, CustomerId, CustomerEmail, CustomerPassword, FirstName, LastName, Gender, BirthDate, null);
        }
        
        /// <remarks/>
        public void RegisterNewUserAsync(string admEmail, string admPassword, int CustomerId, string CustomerEmail, string CustomerPassword, string FirstName, string LastName, int Gender, int BirthDate, object userState) {
            if ((this.RegisterNewUserOperationCompleted == null)) {
                this.RegisterNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterNewUserOperationCompleted);
            }
            this.InvokeAsync("RegisterNewUser", new object[] {
                        admEmail,
                        admPassword,
                        CustomerId,
                        CustomerEmail,
                        CustomerPassword,
                        FirstName,
                        LastName,
                        Gender,
                        BirthDate}, this.RegisterNewUserOperationCompleted, userState);
        }
        
        private void OnRegisterNewUserOperationCompleted(object arg) {
            if ((this.RegisterNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterNewUserCompleted(this, new RegisterNewUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFriendsRequests", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetFriendsRequests(string admEmail, string admPassword, int Customerid, int tops, string sort) {
            object[] results = this.Invoke("GetFriendsRequests", new object[] {
                        admEmail,
                        admPassword,
                        Customerid,
                        tops,
                        sort});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetFriendsRequestsAsync(string admEmail, string admPassword, int Customerid, int tops, string sort) {
            this.GetFriendsRequestsAsync(admEmail, admPassword, Customerid, tops, sort, null);
        }
        
        /// <remarks/>
        public void GetFriendsRequestsAsync(string admEmail, string admPassword, int Customerid, int tops, string sort, object userState) {
            if ((this.GetFriendsRequestsOperationCompleted == null)) {
                this.GetFriendsRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFriendsRequestsOperationCompleted);
            }
            this.InvokeAsync("GetFriendsRequests", new object[] {
                        admEmail,
                        admPassword,
                        Customerid,
                        tops,
                        sort}, this.GetFriendsRequestsOperationCompleted, userState);
        }
        
        private void OnGetFriendsRequestsOperationCompleted(object arg) {
            if ((this.GetFriendsRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFriendsRequestsCompleted(this, new GetFriendsRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFriendsRequestsSeeMore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetFriendsRequestsSeeMore(string admEmail, string admPassword, int Customerid, int linkid, int tops, string sort) {
            object[] results = this.Invoke("GetFriendsRequestsSeeMore", new object[] {
                        admEmail,
                        admPassword,
                        Customerid,
                        linkid,
                        tops,
                        sort});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetFriendsRequestsSeeMoreAsync(string admEmail, string admPassword, int Customerid, int linkid, int tops, string sort) {
            this.GetFriendsRequestsSeeMoreAsync(admEmail, admPassword, Customerid, linkid, tops, sort, null);
        }
        
        /// <remarks/>
        public void GetFriendsRequestsSeeMoreAsync(string admEmail, string admPassword, int Customerid, int linkid, int tops, string sort, object userState) {
            if ((this.GetFriendsRequestsSeeMoreOperationCompleted == null)) {
                this.GetFriendsRequestsSeeMoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFriendsRequestsSeeMoreOperationCompleted);
            }
            this.InvokeAsync("GetFriendsRequestsSeeMore", new object[] {
                        admEmail,
                        admPassword,
                        Customerid,
                        linkid,
                        tops,
                        sort}, this.GetFriendsRequestsSeeMoreOperationCompleted, userState);
        }
        
        private void OnGetFriendsRequestsSeeMoreOperationCompleted(object arg) {
            if ((this.GetFriendsRequestsSeeMoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFriendsRequestsSeeMoreCompleted(this, new GetFriendsRequestsSeeMoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFriendsRequestsCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetFriendsRequestsCount(string admEmail, string admPassword, int Customerid) {
            object[] results = this.Invoke("GetFriendsRequestsCount", new object[] {
                        admEmail,
                        admPassword,
                        Customerid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetFriendsRequestsCountAsync(string admEmail, string admPassword, int Customerid) {
            this.GetFriendsRequestsCountAsync(admEmail, admPassword, Customerid, null);
        }
        
        /// <remarks/>
        public void GetFriendsRequestsCountAsync(string admEmail, string admPassword, int Customerid, object userState) {
            if ((this.GetFriendsRequestsCountOperationCompleted == null)) {
                this.GetFriendsRequestsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFriendsRequestsCountOperationCompleted);
            }
            this.InvokeAsync("GetFriendsRequestsCount", new object[] {
                        admEmail,
                        admPassword,
                        Customerid}, this.GetFriendsRequestsCountOperationCompleted, userState);
        }
        
        private void OnGetFriendsRequestsCountOperationCompleted(object arg) {
            if ((this.GetFriendsRequestsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFriendsRequestsCountCompleted(this, new GetFriendsRequestsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCustomerData(string admEmail, string admPassword, int Customerid) {
            object[] results = this.Invoke("GetCustomerData", new object[] {
                        admEmail,
                        admPassword,
                        Customerid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerDataAsync(string admEmail, string admPassword, int Customerid) {
            this.GetCustomerDataAsync(admEmail, admPassword, Customerid, null);
        }
        
        /// <remarks/>
        public void GetCustomerDataAsync(string admEmail, string admPassword, int Customerid, object userState) {
            if ((this.GetCustomerDataOperationCompleted == null)) {
                this.GetCustomerDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerDataOperationCompleted);
            }
            this.InvokeAsync("GetCustomerData", new object[] {
                        admEmail,
                        admPassword,
                        Customerid}, this.GetCustomerDataOperationCompleted, userState);
        }
        
        private void OnGetCustomerDataOperationCompleted(object arg) {
            if ((this.GetCustomerDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerDataCompleted(this, new GetCustomerDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveCustomerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveCustomerInfo(string admEmail, string admPassword, int Customerid, string FirstName, string LastName, string BirthDate, string Email) {
            this.Invoke("SaveCustomerInfo", new object[] {
                        admEmail,
                        admPassword,
                        Customerid,
                        FirstName,
                        LastName,
                        BirthDate,
                        Email});
        }
        
        /// <remarks/>
        public void SaveCustomerInfoAsync(string admEmail, string admPassword, int Customerid, string FirstName, string LastName, string BirthDate, string Email) {
            this.SaveCustomerInfoAsync(admEmail, admPassword, Customerid, FirstName, LastName, BirthDate, Email, null);
        }
        
        /// <remarks/>
        public void SaveCustomerInfoAsync(string admEmail, string admPassword, int Customerid, string FirstName, string LastName, string BirthDate, string Email, object userState) {
            if ((this.SaveCustomerInfoOperationCompleted == null)) {
                this.SaveCustomerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCustomerInfoOperationCompleted);
            }
            this.InvokeAsync("SaveCustomerInfo", new object[] {
                        admEmail,
                        admPassword,
                        Customerid,
                        FirstName,
                        LastName,
                        BirthDate,
                        Email}, this.SaveCustomerInfoOperationCompleted, userState);
        }
        
        private void OnSaveCustomerInfoOperationCompleted(object arg) {
            if ((this.SaveCustomerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCustomerInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccetpFriendShip", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AccetpFriendShip(string admEmail, string admPassword, int linkid) {
            object[] results = this.Invoke("AccetpFriendShip", new object[] {
                        admEmail,
                        admPassword,
                        linkid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AccetpFriendShipAsync(string admEmail, string admPassword, int linkid) {
            this.AccetpFriendShipAsync(admEmail, admPassword, linkid, null);
        }
        
        /// <remarks/>
        public void AccetpFriendShipAsync(string admEmail, string admPassword, int linkid, object userState) {
            if ((this.AccetpFriendShipOperationCompleted == null)) {
                this.AccetpFriendShipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccetpFriendShipOperationCompleted);
            }
            this.InvokeAsync("AccetpFriendShip", new object[] {
                        admEmail,
                        admPassword,
                        linkid}, this.AccetpFriendShipOperationCompleted, userState);
        }
        
        private void OnAccetpFriendShipOperationCompleted(object arg) {
            if ((this.AccetpFriendShipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccetpFriendShipCompleted(this, new AccetpFriendShipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelFriendShip", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CancelFriendShip(string admEmail, string admPassword, int linkid) {
            object[] results = this.Invoke("CancelFriendShip", new object[] {
                        admEmail,
                        admPassword,
                        linkid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CancelFriendShipAsync(string admEmail, string admPassword, int linkid) {
            this.CancelFriendShipAsync(admEmail, admPassword, linkid, null);
        }
        
        /// <remarks/>
        public void CancelFriendShipAsync(string admEmail, string admPassword, int linkid, object userState) {
            if ((this.CancelFriendShipOperationCompleted == null)) {
                this.CancelFriendShipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelFriendShipOperationCompleted);
            }
            this.InvokeAsync("CancelFriendShip", new object[] {
                        admEmail,
                        admPassword,
                        linkid}, this.CancelFriendShipOperationCompleted, userState);
        }
        
        private void OnCancelFriendShipOperationCompleted(object arg) {
            if ((this.CancelFriendShipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelFriendShipCompleted(this, new CancelFriendShipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastNotifications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetLastNotifications(string admEmail, string admPassword, int customerid) {
            object[] results = this.Invoke("GetLastNotifications", new object[] {
                        admEmail,
                        admPassword,
                        customerid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastNotificationsAsync(string admEmail, string admPassword, int customerid) {
            this.GetLastNotificationsAsync(admEmail, admPassword, customerid, null);
        }
        
        /// <remarks/>
        public void GetLastNotificationsAsync(string admEmail, string admPassword, int customerid, object userState) {
            if ((this.GetLastNotificationsOperationCompleted == null)) {
                this.GetLastNotificationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastNotificationsOperationCompleted);
            }
            this.InvokeAsync("GetLastNotifications", new object[] {
                        admEmail,
                        admPassword,
                        customerid}, this.GetLastNotificationsOperationCompleted, userState);
        }
        
        private void OnGetLastNotificationsOperationCompleted(object arg) {
            if ((this.GetLastNotificationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastNotificationsCompleted(this, new GetLastNotificationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerLink", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCustomerLink(string admEmail, string admPassword, int customerid) {
            object[] results = this.Invoke("GetCustomerLink", new object[] {
                        admEmail,
                        admPassword,
                        customerid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerLinkAsync(string admEmail, string admPassword, int customerid) {
            this.GetCustomerLinkAsync(admEmail, admPassword, customerid, null);
        }
        
        /// <remarks/>
        public void GetCustomerLinkAsync(string admEmail, string admPassword, int customerid, object userState) {
            if ((this.GetCustomerLinkOperationCompleted == null)) {
                this.GetCustomerLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerLinkOperationCompleted);
            }
            this.InvokeAsync("GetCustomerLink", new object[] {
                        admEmail,
                        admPassword,
                        customerid}, this.GetCustomerLinkOperationCompleted, userState);
        }
        
        private void OnGetCustomerLinkOperationCompleted(object arg) {
            if ((this.GetCustomerLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerLinkCompleted(this, new GetCustomerLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncreaseNotificationCounter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IncreaseNotificationCounter(string admEmail, string admPassword, int other_userid, int type) {
            object[] results = this.Invoke("IncreaseNotificationCounter", new object[] {
                        admEmail,
                        admPassword,
                        other_userid,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IncreaseNotificationCounterAsync(string admEmail, string admPassword, int other_userid, int type) {
            this.IncreaseNotificationCounterAsync(admEmail, admPassword, other_userid, type, null);
        }
        
        /// <remarks/>
        public void IncreaseNotificationCounterAsync(string admEmail, string admPassword, int other_userid, int type, object userState) {
            if ((this.IncreaseNotificationCounterOperationCompleted == null)) {
                this.IncreaseNotificationCounterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncreaseNotificationCounterOperationCompleted);
            }
            this.InvokeAsync("IncreaseNotificationCounter", new object[] {
                        admEmail,
                        admPassword,
                        other_userid,
                        type}, this.IncreaseNotificationCounterOperationCompleted, userState);
        }
        
        private void OnIncreaseNotificationCounterOperationCompleted(object arg) {
            if ((this.IncreaseNotificationCounterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncreaseNotificationCounterCompleted(this, new IncreaseNotificationCounterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificationsCountZero", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotificationsCountZero(string admEmail, string admPassword, int type) {
            object[] results = this.Invoke("NotificationsCountZero", new object[] {
                        admEmail,
                        admPassword,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotificationsCountZeroAsync(string admEmail, string admPassword, int type) {
            this.NotificationsCountZeroAsync(admEmail, admPassword, type, null);
        }
        
        /// <remarks/>
        public void NotificationsCountZeroAsync(string admEmail, string admPassword, int type, object userState) {
            if ((this.NotificationsCountZeroOperationCompleted == null)) {
                this.NotificationsCountZeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificationsCountZeroOperationCompleted);
            }
            this.InvokeAsync("NotificationsCountZero", new object[] {
                        admEmail,
                        admPassword,
                        type}, this.NotificationsCountZeroOperationCompleted, userState);
        }
        
        private void OnNotificationsCountZeroOperationCompleted(object arg) {
            if ((this.NotificationsCountZeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificationsCountZeroCompleted(this, new NotificationsCountZeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNotificationCounts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNotificationCounts(string admEmail, string admPassword, int type) {
            object[] results = this.Invoke("GetNotificationCounts", new object[] {
                        admEmail,
                        admPassword,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNotificationCountsAsync(string admEmail, string admPassword, int type) {
            this.GetNotificationCountsAsync(admEmail, admPassword, type, null);
        }
        
        /// <remarks/>
        public void GetNotificationCountsAsync(string admEmail, string admPassword, int type, object userState) {
            if ((this.GetNotificationCountsOperationCompleted == null)) {
                this.GetNotificationCountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNotificationCountsOperationCompleted);
            }
            this.InvokeAsync("GetNotificationCounts", new object[] {
                        admEmail,
                        admPassword,
                        type}, this.GetNotificationCountsOperationCompleted, userState);
        }
        
        private void OnGetNotificationCountsOperationCompleted(object arg) {
            if ((this.GetNotificationCountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNotificationCountsCompleted(this, new GetNotificationCountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RegisterNewUserCompletedEventHandler(object sender, RegisterNewUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetFriendsRequestsCompletedEventHandler(object sender, GetFriendsRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFriendsRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFriendsRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetFriendsRequestsSeeMoreCompletedEventHandler(object sender, GetFriendsRequestsSeeMoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFriendsRequestsSeeMoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFriendsRequestsSeeMoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetFriendsRequestsCountCompletedEventHandler(object sender, GetFriendsRequestsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFriendsRequestsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFriendsRequestsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCustomerDataCompletedEventHandler(object sender, GetCustomerDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SaveCustomerInfoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AccetpFriendShipCompletedEventHandler(object sender, AccetpFriendShipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccetpFriendShipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccetpFriendShipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CancelFriendShipCompletedEventHandler(object sender, CancelFriendShipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelFriendShipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelFriendShipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetLastNotificationsCompletedEventHandler(object sender, GetLastNotificationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastNotificationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastNotificationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCustomerLinkCompletedEventHandler(object sender, GetCustomerLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void IncreaseNotificationCounterCompletedEventHandler(object sender, IncreaseNotificationCounterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncreaseNotificationCounterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncreaseNotificationCounterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void NotificationsCountZeroCompletedEventHandler(object sender, NotificationsCountZeroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotificationsCountZeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotificationsCountZeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetNotificationCountsCompletedEventHandler(object sender, GetNotificationCountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNotificationCountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNotificationCountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591